    ('12 LUNAS BLANCO', 'D.O. Somontano'),
    ('12 LUNAS GARNACHA', 'D.O. Somontano'),
    ('12 LUNAS ROSADO', 'D.O. Somontano'),
    ('12 LUNAS TINTO', 'D.O. Somontano'),
    ('ABADÍA DE SAN CAMPÍO', 'D.O. Rías Baixas'),
    ('AC', 'D.O. Rioja'),
    ('AC 5.5', 'D.O. Rioja'),
    ('ALTAMIMBRE 2016', 'D.O. Ribera del Duero'),
    ('ARENISCA', 'IGP Castilla y León'),
    ('ARTUKE', 'D.O. Rioja'),
    ('ASTRALES', 'D.O. Ribera del Duero'),
    ('ASTRALES CHRISTINA', 'D.O. Ribera del Duero'),
    ('AUREA', 'D.O. Bierzo'),
    ('BAELO 12', 'D.O. Tierra de Cádiz'),
    ('BAELO 24', 'D.O. Tierra de Cádiz'),
    ('BAYNOS', 'D.O. Castilla León'),
    ('BAYNOS BLANCO', 'D.O. Castilla León'),
    ('BENTO ORGÁNICO', 'D.O. Rueda'),
    ('BIGARDO', 'D.O. Toro'),
    ('BLANC DE BLANCS', 'D.O. Conca del Riu Anoia'),
    ('BLANCO', 'D.O. Rioja'),
    ('BLANQUITO', 'D.O. Rías Baixas'),
    ('BLUE CAP', 'D.O. Ribera del Duero'),
    ('BOCCA PAYASO', 'D.O. Ribera del Duero'),
    ('BOTÓN DE GALLO ROSADO', 'D.O. Rueda'),
    ('BOTÓN DE GALLO VERDEJO', 'D.O. Rueda'),
    ('BULERÍA BLANCO', 'D.O. Tierra de Cádiz'),
    ('BULERÍA TINTO', 'D.O. Tierra de Cádiz'),
    ('CALMA', 'D.O. Toro'),
    ('CALZADAS', 'D.O. Rioja'),
    ('CAMPANO', 'D.O. Tierra de Cádiz'),
    ('CANTAYANO', 'IGP Castilla y León'),
    ('CANTO DEL GRILLO', 'D.O. Somontano'),
    ('CARRAMIMBRE CRIANZA 2018', 'D.O. Ribera del Duero'),
    ('CARRAMIMBRE RESERVA', 'D.O. Ribera del Duero'),
    ('CARRAMIMBRE ROBLE 202', 'D.O. Ribera del Duero'),
    ('CARRAMIMBRE ROSADO 2022', 'D.O. Cigales'),
    ('CARRAMIMBRE VERDEJO 2020', 'D.O. Verdejo'),
    ('CARTAGO', 'D.O. Toro'),
    ('CITIUS', 'D.O. Castilla León'),
    ('COLLECTION', 'D.O. Ribera del Duero'),
    ('COLLECTION RUEDA', 'D.O. Rueda'),
    ('COORDENADAS', 'D.O. Rioja'),
    ('CRIANZA', 'D.O. Rioja'),
    ('CRIANZA RIBERA', 'D.O. Ribera del Ruedo'),
    ('CRIANZA RIOJA', 'D.O. Rioja'),
    ('DE LA FINCA', 'D.O. Conca del Riu Anoia'),
    ('DENIT', 'D.O. Conca del Riu Anoia'),
    ('DESPIERTA CABERNET SAUVIGNON', 'D.O. Castilla León'),
    ('DESPIERTA SAUVIGNON BLANC', 'D.O. Castilla León'),
    ('DESPIERTA TEMPRANILLO', 'D.O. Castilla León'),
    ('DESPIERTA VERDEJO', 'D.O. Castilla León'),
    ('DOS ALAS ROJAS', 'D.O. Ribera del Duero'),
    ('EL ESCOLLADERO', 'D.O. Rioja'),
    ('EL JARDÍN DE LA EMPERATRIZ BLANCO', 'D.O. Rioja'),
    ('EL JARDÍN DE LA EMPERATRIZ TINTO', 'D.O. Rioja'),
    ('EL PEDAL', 'D.O. Rioja'),
    ('EL SENTIDO DE LA VIDA', 'D.O. Jumilla'),
    ('EL TIEMPO QUE NOS UNE', 'D.O. Jumilla'),
    ('ETERNAUTA', 'D.O. Ribera del Duero'),
    ('FINCA DE LOS LOCOS', 'D.O. Rioja'),
    ('FINCA ESTARIJO', 'D.O. Rioja'),
    ('FINCA LA EMPERATRIZ BLANCO', 'D.O. Rioja'),
    ('FINCA LA EMPERATRIZ TINTO', 'D.O. Rioja'),
    ('FINO MICAELA', 'D.O. Jerez-Xérès-Sherry'),
    ('GARMÓN', 'D.O. Ribera del Duero'),
    ('GARNACHA PROMETIDA', 'D.O. Rioja'),
    ('GODELLO', 'D.O. Valdeorras'),
    ('GODELLO SOBRE LÍAS', 'D.O. Valdeorras'),
    ('GRACIANO', 'D.O. Rioja'),
    ('GRILLO', 'D.O. Somontano'),
    ('GRILLO SP', 'D.O. Somontano'),
    ('HOP HOP', 'D.O. Somontano'),
    ('INSPIRATION', 'D.O. Ribera del Duero'),
    ('JOVEN RIBERA', 'D.O. Ribera del Ruedo'),
    ('JOVEN RIOJA', 'D.O. Rioja'),
    ('LA BATALLA DE LA BARROSA', 'D.O. Tierra de Cádiz'),
    ('LA CALERA DEL ESCARAMUJO', 'D.O. Jumilla'),
    ('LA CONDENADA', 'D.O. Rioja'),
    ('LA MAR', 'D.O. Rías Baixas'),
    ('LA MARAGATA', 'D.O. Bierzo'),
    ('LA OTEA', 'IGP Castilla y León'),
    ('LA PROHIBICIÓN', 'D.O. Bierzo'),
    ('LA PROHIBICIÓN DULCE', 'D.O. Castilla y León'),
    ('LA PROHIBICIÓN PALOMINO FINO', 'D.O. Bierzo'),
    ('LA RABIA', 'D.O. Jumilla'),
    ('LA RODETTA CRIANZA', 'D.O. Rioja'),
    ('LA RODETTA VERDEJO', 'D.O. Rueda'),
    ('LA SERVIL', 'D.O. Jumilla'),
    ('LAS CENIZAS', 'D.O. Rioja'),
    ('LOS YESARES', 'D.O. Jumilla'),
    ('LUMA', 'D.O. Ribera del Duero'),
    ('LUNA BLANCA', 'D.O. Rueda'),
    ('MAJUELO DEL CHIRIVITERO', 'IGP Castilla y León'),
    ('MAJUELO EL ESPEJO', 'IGP Castilla y León'),
    ('MALDITO PARNÉ', 'D.O. Toro'),
    ('MANUEL', 'D.O. Conca del Riu Anoia'),
    ('MANZANILLA MICAELA', 'D.O. Manzanilla-Sanlúcar de Barrameda'),
    ('MAS DEL SERRAL', 'D.O. Conca del Riu Anoia'),
    ('MATAS ALTAS', 'D.O. Jumilla'),
    ('MAURO', 'D.O. Castilla León'),
    ('MAURO GODELLO', 'D.O. Castilla León'),
    ('MAURO VS', 'D.O. Castilla León'),
    ('MOMENTO', 'D.O. Rioja'),
    ('MOSCATEL GLORIA', 'D.O. Tierra de Cádiz'),
    ('PALO CORTADO MICAELA', 'D.O. Jerez-Xérès-Sherry'),
    ('PÁRPADOS', 'D.O. Ribera del Duero'),
    ('PASO LAS MAÑAS', 'D.O. Rioja'),
    ('PAVINA TINTO', 'D.O. Castilla León'),
    ('PELLEJO', 'D.O. Toro'),
    ('PETIT', 'D.O. Bierzo'),
    ('PIES NEGROS', 'D.O. Rioja'),
    ('PINOT NOIR', 'D.O. Castilla León'),
    ('PINOT NOIR ROSÉ', 'D.O. Castilla León'),
    ('PITTACUM', 'D.O. Bierzo'),
    ('PONTELLÓN', 'D.O. Rías Baixas'),
    ('PRIMA', 'D.O. Toro'),
    ('QS2', 'D.O. Castilla y León'),
    ('QUINTA SARDONIA', 'D.O. Castilla y León'),
    ('RAÚL CALVO JOVEN', 'D.O. Ribera del Duero'),
    ('RAÚL CALVO ROBLE', 'D.O. Ribera del Duero'),
    ('REMORDIMIENTO', 'D.O. Jumilla'),
    ('REMORDIMIENTO BLANCO', 'D.O. Jumilla'),
    ('RESERVA', 'D.O. Rioja'),
    ('RIBERA ROBLE', 'D.O. Ribera del Ruedo'),
    ('SAN ROMÁN', 'D.O. Toro'),
    ('SARDÓN', 'D.O. Castilla y León'),
    ('SATÉLITE', 'D.O. Toro'),
    ('SILGA', 'D.O. Rueda'),
    ('TARANTELO CHARDONNAY', 'D.O. Tierra de Cádiz'),
    ('TARANTELO TINTO', 'D.O. Tierra de Cádiz'),
    ('TERRAS GAUDA', 'D.O. Rías Baixas'),
    ('TERRAS GAUDA ETIQUETA NEGRA', 'D.O. Rías Baixas'),
    ('TERREUS', 'D.O. Castilla León'),
    ('TEXTURES DE PEDRA', 'D.O. Conca del Riu Anoia'),
    ('TINTO', 'D.O. Rioja'),
    ('TODO SOBRE MI', 'D.O. Jumilla'),
    ('TRASCUEVAS', 'D.O. Rioja'),
    ('VAL DE LA OSA', 'D.O. Bierzo'),
    ('VALEYO', 'D.O. Bierzo'),
    ('VERDEJO', 'D.O. Rueda'),
    ('VERDEJO RUEDA', 'D.O. Rueda'),
    ('VERMUT ARTESANO', 'D.O. Tierra de Cádiz'),
    ('XIXARITO AMONTILLADO', 'D.O. Jerez-Xérès-Sherry'),
    ('XIXARITO CREAM', 'D.O. Jerez-Xérès-Sherry'),
    ('XIXARITO FINO', 'D.O. Jerez-Xérès-Sherry'),
    ('XIXARITO MANZANILLA', 'D.O. Manzanilla-Sanlúcar de Barrameda'),
    ('XIXARITO MEDIUM', 'D.O. Jerez-Xérès-Sherry'),
    ('XIXARITO OLOROSO', 'D.O. Jerez-Xérès-Sherry'),
    ('XIXARITO PALO CORTADO', 'D.O. Jerez-Xérès-Sherry'),
    ('XIXARITO PEDRO XIMÉNEZ', 'D.O. Jerez-Xérès-Sherry')
